---
- name: Configure ipa clients

  hosts: ipa_client

  become: true

  vars:

    ipaclient_force_join: yes

  roles:

    - role: ipaclient
      when:
        - not 'ipa_server' in group_names
        - not 'ipa_replica' in group_names

  vars:

    state: "{{ 'absent' if (ipaclient_uninstall | default('no') | bool) else 'present' }}"
