---
- name: Configure ipa replicas

  hosts: ipa_replica

  become: true

  vars:

    ipareplica_setup_ca: yes
    ipareplica_setup_dns: yes
    ipareplica_auto_forwarders: yes
    ipareplica_setup_firewalld: no
    ipareplica_allow_zone_overlap: yes
    ipareplica_no_dnssec_validation: yes
    ipareplica_setup_adtrust: yes
    ipaclient_force_join: yes
    ipaclient_mkhomedir: yes

  roles:

    - bertvv.hosts
    - ipareplica

  tasks:

    - name: work around ipareplica dns forwarding errors before reboot
      reboot:

    - name: disable hardcoded apache redirects in freeipa vhost
      replace:
        path: /etc/httpd/conf.d/ipa-rewrite.conf
        regexp: '{{ item.regexp }}'
        replace: '{{ item.replace }}'
      loop_control:
        label: "{{ item.regexp }}"
      loop:
        - regexp: '^(RewriteRule \^/\$) (https://.*)(/ipa/ui.*)$'
          replace: '\1 \3'
        - regexp: '^(RewriteRule \^\/ipa\/\(.*)$'
          replace: '#\1'
        - regexp: '^(RewriteCond .*)$'
          replace: '#\1'
      become: true

  handlers:

    - name: restart apache
      service:
        name: httpd
        state: restarted
