---
- name: Install project prerequisites

  hosts: localhost

  tasks:

    - name: install requirements
      command: pip install -r requirements.txt

    - name: install ansible galaxy roles
      command: ansible-galaxy install -r roles/requirements.yml -p galaxy/ --force

    - name: run ansible galaxy collections
      command: ansible-galaxy install -r collections/requirements.yml
