---
- name: Manage freeipa users

  hosts: ipa_user

  gather_facts: no

  become: yes

  roles:

    - nephelaiio.plugins

  tasks:

    - name: bootstrap ipa groups
      ipa_group:
        ipa_user: "{{ ipaadmin_principal }}"
        ipa_pass: "{{ ipaadmin_password }}"
        ipa_host: "{{ ipauser_host | default('omit') }}"
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
      loop_control:
        label: "{{ item.name | default('None') }}"
      loop: "{{ ipa_groups }}"
      delegate_to: "{{ groups['ipa_server'] | first }}"
      when:
        - ipa_groups is defined

    - name: create ipa users
      ipa_user:
        ipa_user: "{{ ipaadmin_principal }}"
        ipa_pass: "{{ ipaadmin_password }}"
        ipa_host: "{{ ipauser_host | default('omit') }}"
        name: "{{ item.user_name }}"
        group: "{{ item.groups | default(omit) }}"
        password: "{{ item.pass }}"
        givenname: "{{ item.first_name }}"
        sn: "{{ item.last_name }}"
        telephonenumber: "{{ item.telephonenumber | default(omit) }}"
        mail: "{{ item.mail | default(omit) }}"
        krbpasswordexpiration: "20230119235959"
        loginshell: /bin/bash
        update_password: "{{ item.update_password | default('on_create') }}"
        state: "{{ item.state | default('present') }}"
      loop_control:
        label: "{{ item.user_name | default('None') }}"
      loop: "{{ ipa_users }}"
      delegate_to: "{{ groups['ipa_server'] | first }}"
      no_log: "{{ not (ipauser_debug | default('no') | bool) }}"
      when:
        - ipa_users is defined

    - name: manage ipa group memberships
      ipa_group:
        ipa_user: "{{ ipaadmin_principal }}"
        ipa_pass: "{{ ipaadmin_password }}"
        ipa_host: "{{ ipauser_host | default('omit') }}"
        name: "{{ item.name }}"
        groups: "{{ item.groups | default(omit) }}"
        user: "{{ item.users | default(omit) }}"
      loop_control:
        label: "{{ item.name | default('None') }}"
      loop: "{{ ipa_groups }}"
      delegate_to: "{{ groups['ipa_server'] | first }}"
      when:
        - ipa_groups is defined
